_wandb:
    value:
        cli_version: 0.21.0
        e:
            dtm26dcpip31cchgf3ztsjqsgre9zs2j:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "102609973248"
                        used: "85608185856"
                email: liyizhou120@gmail.com
                executable: /media/yizhouli/1TB 970 Evo Plus/code/cs336/assignment1-basics-main/.venv/bin/python3
                host: yizhouli-rog-g15
                memory:
                    total: "33023422464"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.35
                program: /media/yizhouli/1TB 970 Evo Plus/code/cs336/assignment1-basics-main/cs336_basics/transformer/train.py
                python: CPython 3.12.7
                root: /media/yizhouli/1TB 970 Evo Plus/code/cs336/assignment1-basics-main/cs336_basics/transformer
                startedAt: "2025-11-24T00:22:08.727335Z"
                writerId: dtm26dcpip31cchgf3ztsjqsgre9zs2j
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.12.7
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
model:
    value:
        context_length: 256
        d_ff: 1344
        d_model: 512
        num_heads: 16
        num_layers: 4
        rope_theta: 10000
        vocab_size: 10000
optimizer:
    value:
        betas:
            - 0.9
            - 0.999
        lr: 0.0003
        max_norm: 1
        weight_decay: 0.01
training:
    value:
        batch_size: 16
        checkpoint_freq: 2000
        log_freq: 10
        total_epochs: 0.5
        val_batch_size: 16
        val_batches: 20
        val_freq: 400
